### ISSUE TITLE
Add an example app

### ISSUE THREAD

**Issue by adriancole** [whitemerry/phpkin#3]
One way for users to get started easily is to show an example app. This also helps people in the zipkin gitter channel help when you aren't around. Finally, it helps show bugs which are otherwise not visible.

maybe something like this (there are a lot of these) https://github.com/openzipkin/pyramid_zipkin-example

**Comment by wansuiye** [comment]
waiting for an example between client and server

**Comment by wansuiye** [comment]
Hello, I'm trying to use phpkin for my project,  I spent two days on it，however it still can't work. Could you give me an example, please?

**Comment by whitemerry** [comment]
@wansuiye sure thing, give me 1 day :)

**Comment by whitemerry** [comment]
@adriancole and @wansuiye
https://github.com/whitemerry/phpkin/tree/master/example/frontend
https://github.com/whitemerry/phpkin/tree/master/example/backend

**Comment by adriancole** [comment]
Hmm does the frontend actually call the backend? It doesnt look like it
does.. almost looks like copy paste..

Usually the frontend calls the backend which shows that the library can not
just create but also parse http tracing headers..
