### ISSUE TITLE
Mark events in Zipkin

### ISSUE THREAD

**Issue by wdalmut** [whitemerry/phpkin#9]
![2017-06-21-11-49-15_3072x413](https://user-images.githubusercontent.com/551974/27378456-3477a290-5678-11e7-8f22-a696775214cb.png)

Hi, it is possibile to mark events (white circle pins in the zipkin timeframes) with your library?

**Comment by whitemerry** [comment]
No, but you can add metadata to span: [time => 33ms] so you will see that data on click. Or create pseudo children spans marking this events one line below like this: "postgresql" but 1 ms long.

Sorry for late answer but i had a lot of work.
